services:
  streamlit:
    image: joshxt/streamlit:latest
    environment:
      AGIXT_URI: ${AGIXT_URI:-http://agixt:7437}
      APP_URI: ${APP_URI:-http://localhost:8501}
      AOL_CLIENT_ID: ${AOL_CLIENT_ID}
      APPLE_CLIENT_ID: ${APPLE_CLIENT_ID}
      AUTODESK_CLIENT_ID: ${AUTODESK_CLIENT_ID}
      AWS_CLIENT_ID: ${AWS_CLIENT_ID}
      AWS_REGION: ${AWS_REGION}
      AWS_USER_POOL_ID: ${AWS_USER_POOL_ID}
      BATTLENET_CLIENT_ID: ${BATTLENET_CLIENT_ID}
      BITBUCKET_CLIENT_ID: ${BITBUCKET_CLIENT_ID}
      BITLY_ACCESS_TOKEN: ${BITLY_ACCESS_TOKEN}
      BITLY_CLIENT_ID: ${BITLY_CLIENT_ID}
      CF_CLIENT_ID: ${CF_CLIENT_ID}
      CLEAR_SCORE_CLIENT_ID: ${CLEAR_SCORE_CLIENT_ID}
      DEUTSCHE_TELKOM_CLIENT_ID: ${DEUTSCHE_TELKOM_CLIENT_ID}
      DEVIANTART_CLIENT_ID: ${DEVIANTART_CLIENT_ID}
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DROPBOX_CLIENT_ID: ${DROPBOX_CLIENT_ID}
      FACEBOOK_CLIENT_ID: ${FACEBOOK_CLIENT_ID}
      FATSECRET_CLIENT_ID: ${FATSECRET_CLIENT_ID}
      FITBIT_CLIENT_ID: ${FITBIT_CLIENT_ID}
      FORMSTACK_CLIENT_ID: ${FORMSTACK_CLIENT_ID}
      FOURSQUARE_CLIENT_ID: ${FOURSQUARE_CLIENT_ID}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITLAB_CLIENT_ID: ${GITLAB_CLIENT_ID}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      HUDDLE_CLIENT_ID: ${HUDDLE_CLIENT_ID}
      IMGUR_CLIENT_ID: ${IMGUR_CLIENT_ID}
      INSTAGRAM_CLIENT_ID: ${INSTAGRAM_CLIENT_ID}
      INTEL_CLIENT_ID: ${INTEL_CLIENT_ID}
      JIVE_CLIENT_ID: ${JIVE_CLIENT_ID}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      LINKEDIN_CLIENT_ID: ${LINKEDIN_CLIENT_ID}
      MICROSOFT_CLIENT_ID: ${MICROSOFT_CLIENT_ID}
      NETIQ_CLIENT_ID: ${NETIQ_CLIENT_ID}
      OKTA_CLIENT_ID: ${OKTA_CLIENT_ID}
      OKTA_DOMAIN: ${OKTA_DOMAIN}
      OPENAM_BASE_URL: ${OPENAM_BASE_URL}
      OPENAM_CLIENT_ID: ${OPENAM_CLIENT_ID}
      ORCID_CLIENT_ID: ${ORCID_CLIENT_ID}
      OSM_CLIENT_ID: ${OSM_CLIENT_ID}
      PAYPAL_CLIENT_ID: ${PAYPAL_CLIENT_ID}
      PING_IDENTITY_CLIENT_ID: ${PING_IDENTITY_CLIENT_ID}
      PIXIV_CLIENT_ID: ${PIXIV_CLIENT_ID}
      REDDIT_CLIENT_ID: ${REDDIT_CLIENT_ID}
      SALESFORCE_CLIENT_ID: ${SALESFORCE_CLIENT_ID}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      STACKEXCHANGE_CLIENT_ID: ${STACKEXCHANGE_CLIENT_ID}
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRIPE_CLIENT_ID: ${STRIPE_CLIENT_ID}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      VIADEO_CLIENT_ID: ${VIADEO_CLIENT_ID}
      VIMEO_CLIENT_ID: ${VIMEO_CLIENT_ID}
      VK_CLIENT_ID: ${VK_CLIENT_ID}
      WECHAT_CLIENT_ID: ${WECHAT_CLIENT_ID}
      WEIBO_CLIENT_ID: ${WEIBO_CLIENT_ID}
      WITHINGS_CLIENT_ID: ${WITHINGS_CLIENT_ID}
      XERO_CLIENT_ID: ${XERO_CLIENT_ID}
      XING_CLIENT_ID: ${XING_CLIENT_ID}
      YAHOO_CLIENT_ID: ${YAHOO_CLIENT_ID}
      YAMMER_CLIENT_ID: ${YAMMER_CLIENT_ID}
      YANDEX_CLIENT_ID: ${YANDEX_CLIENT_ID}
      YELP_CLIENT_ID: ${YELP_CLIENT_ID}
      ZENDESK_CLIENT_ID: ${ZENDESK_CLIENT_ID}
      ZENDESK_SUBDOMAIN: ${ZENDESK_SUBDOMAIN}
      TZ: ${TZ:-America/New_York}
    ports:
      - "8501:8501"
